### ISSUE TITLE
downloading tweets

### ISSUE THREAD

**Issue by paarasbhandari** [SakibShahriar95/ANTiVax#2]
Hi, do you have a script for downloading the tweets? I get a 'too many requests' error when I try downloading the tweets from the csv file in labelled

**Comment by sakibsh** [comment]
The ids file will now be available, please follow the script below:

twarc hydrate ids.txt tweets.jsonl
twarc csv --output-columns "id,created_at,text,author.location" --no-inline-referenced-tweets 'tweets.jsonl' 'tweets.csv'
